dist: focal
language: python
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libssl-dev
before_install:
- openssl aes-256-cbc -K $encrypted_d2c3095c119c_key -iv $encrypted_d2c3095c119c_iv
  -in passwords.py.enc -out tests/passwords.py -d
script:
- python3 -m unittest discover
stages:
- deploy
deploy:
  provider: pypi
  user: __token__
  password:
    secure: gSZT+anRwz7d8a8HgGcVEY8n1sIJeEN0eS6WuB0QZg3zJ3GNmtoLCCe94EVd1IAvbjXUf198xKhS/3Rq8uZ/8NG7AFrS2S2piJ95CBxlpZZX50plGk2QufVDxDmdLfDMlBOmLuyrHfLb8CiPjf8PX+muXJtiRbLUtWY42k7gUTM5h7v3Y6bOrtta2+pKFnJOx7c/oLalybmUKWYLmLOlytx+Syle0XsY3waq5uKzhONrH8KhV/w0wOSAvdtb83R1DF/nXxLaoqJPT3kHmYxQ6MgTBNg6PqS/amjhPgqXhI/OZP2GWiHqiTZjux7Pp7cQ7ELUBuY191J3OVuu5lxwX7Zh1BU3tcjOopOL4Zv/XWBibZL0lqxlD91FVwGJMWkdrvioKccrrbua0ztwWTjb85BHMnitDLz+n1ajRxUWllq1/u1pBtD6PumJAHW3K1JXfcBa30vSFXBbhjLHjn1uqHj1AglSjBjw3a3Dpw23FAtPbgRaKD4HofzuLnGDX1w/r/JVp6g/3uFRsauo022yGqUuyluVmG8VwNohZxjaGdVyiOnJopW+Ur5qi9B0As1SXS78pkrA2qsEJMDwKwhQtOqkruOYpl10xKA9jgOVsmOsGkAw65adZ4k5xMS545b5E9BKXtaTG08jgS9FGk/K2uW5AP2ynDqthNgwVHQhvYQ=
